package org.example.lazarusplugin.actions

import com.intellij.openapi.actionSystem.AnAction
import com.intellij.openapi.actionSystem.AnActionEvent
import com.intellij.openapi.actionSystem.ActionUpdateThread
import com.intellij.openapi.actionSystem.CommonDataKeys
import com.intellij.openapi.components.service
import org.example.lazarusplugin.services.api.IGraphStorage
import org.example.lazarusplugin.ui.MarkdownReportDialog

class FileSemReportAction : AnAction("Generate Semantic Report") {

    override fun getActionUpdateThread(): ActionUpdateThread {
        return ActionUpdateThread.BGT
    }

    override fun actionPerformed(e: AnActionEvent) {
        val editor = e.getData(CommonDataKeys.EDITOR)
        val psiFile = e.getData(CommonDataKeys.PSI_FILE)
        val project = e.project

        if (editor == null || psiFile == null || project == null) {
            return
        }

        // Dummy markdown content
        val markdownContent = """
# Semantic Report for ${psiFile.name}

## File Information
- **Path**: `${psiFile.virtualFile.path}`
- **Language**: ${psiFile.language.displayName}

## Analysis

### Overview
This is a dummy semantic analysis report. In production, this would contain:
- Code structure analysis
- Dependencies
- Complexity metrics
- Potential issues

### Code Statistics
- Lines of code: TBD
- Functions: TBD
- Classes: TBD

### Dependencies
- Internal dependencies: TBD
- External dependencies: TBD

---
*Generated by Lazarus Plugin*
        """.trimIndent()

        // Show dialog with markdown content
        val dialog = MarkdownReportDialog(
            project = project,
            title = "Semantic Report - ${psiFile.name}",
            markdownContent = markdownContent
        )
        dialog.show()
    }

    override fun update(e: AnActionEvent) {
        val project = e.project
        val editor = e.getData(CommonDataKeys.EDITOR)
        val psiFile = e.getData(CommonDataKeys.PSI_FILE)

        // Action is enabled only if file is open AND graph is ready
        val graphReady = project?.service<IGraphStorage>()?.isGraphReady() ?: false
        e.presentation.isEnabledAndVisible = editor != null && psiFile != null && graphReady
    }
}
