package org.example.lazarusplugin.actions

import com.intellij.openapi.actionSystem.AnAction
import com.intellij.openapi.actionSystem.AnActionEvent
import com.intellij.openapi.actionSystem.ActionUpdateThread
import com.intellij.openapi.components.service
import org.example.lazarusplugin.services.api.GraphStorage
import org.example.lazarusplugin.ui.MarkdownReportDialog

class GitDiffSemReportAction : AnAction("Fetch & Compare Semantics") {

    override fun getActionUpdateThread(): ActionUpdateThread {
        return ActionUpdateThread.BGT
    }

    override fun actionPerformed(e: AnActionEvent) {
        val project = e.project ?: return

        // Dummy markdown content for git diff semantic analysis
        val markdownContent = """
# Git Semantic Diff Report

## Remote to HEAD Comparison

### Overview
This report shows semantic differences between the remote branch and your current HEAD.

### Changes Summary
- **Files modified**: TBD
- **Functions added**: TBD
- **Functions removed**: TBD
- **Classes changed**: TBD

### Semantic Changes

#### New Features
- TBD

#### Breaking Changes
- TBD

#### Refactorings
- TBD

### Detailed Analysis

#### Modified Files
1. **File 1**: `path/to/file1.kt`
   - Function `foo()` signature changed
   - New class `Bar` added

2. **File 2**: `path/to/file2.kt`
   - Method `process()` removed
   - Interface implementation changed

### Impact Analysis
- **API Compatibility**: TBD
- **Behavioral Changes**: TBD
- **Performance Impact**: TBD

---
*Generated by Lazarus Plugin*
        """.trimIndent()

        // Show dialog with markdown content and merge button
        val dialog = MarkdownReportDialog(
            project = project,
            title = "Git Semantic Diff Report",
            markdownContent = markdownContent
        )
        dialog.show()
    }

    override fun update(e: AnActionEvent) {
        val project = e.project
        // Action is always visible but only enabled when graph is ready
        val graphReady = project?.service<GraphStorage>()?.isGraphReady() ?: false
        e.presentation.isVisible = project != null
        e.presentation.isEnabled = graphReady
    }
}
