package org.example.lazarusplugin.actions

import com.intellij.openapi.actionSystem.AnAction
import com.intellij.openapi.actionSystem.AnActionEvent
import com.intellij.openapi.actionSystem.ActionUpdateThread
import com.intellij.openapi.components.service
import org.example.lazarusplugin.services.api.GraphStorage
import org.example.lazarusplugin.ui.MarkdownReportDialog

class GlobalSemReportAction : AnAction("Generate Global Semantic Report") {

    override fun getActionUpdateThread(): ActionUpdateThread {
        return ActionUpdateThread.BGT
    }

    override fun actionPerformed(e: AnActionEvent) {
        val project = e.project ?: return

        // Dummy markdown content for global codebase analysis
        val markdownContent = """
# Global Semantic Report

## Project Overview
- **Project Name**: ${project.name}
- **Base Path**: `${project.basePath}`

## Codebase Analysis

### Project Structure
- Total modules: TBD
- Total files: TBD
- Lines of code: TBD

### Architecture Overview
- Main packages: TBD
- Entry points: TBD
- Key components: TBD

### Dependencies
- External libraries: TBD
- Internal dependencies graph: TBD

### Code Quality Metrics
- Complexity score: TBD
- Technical debt: TBD
- Test coverage: TBD

### Potential Issues
- Unused code: TBD
- Circular dependencies: TBD
- Performance bottlenecks: TBD

---
*Generated by Lazarus Plugin*
        """.trimIndent()

        // Show dialog with markdown content
        val dialog = MarkdownReportDialog(
            project = project,
            title = "Global Semantic Report - ${project.name}",
            markdownContent = markdownContent
        )
        dialog.show()
    }

    override fun update(e: AnActionEvent) {
        val project = e.project
        // Action is always visible but only enabled when graph is ready
        val graphReady = project?.service<GraphStorage>()?.isGraphReady() ?: false
        e.presentation.isVisible = project != null
        e.presentation.isEnabled = graphReady
    }
}
